const data = [
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
  { name: "kazi nayeem", email: "kazinayeem@gmail.com" },
];



export default data;